on:
  release:
    types:
      - created

    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: https://uploads.github.com/repos/$GITHUB_REPOSITORY/releases/1/assets{?name,label}"
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
        asset_path: ./$REPO_NAME.zip
        asset_name: $REPO_NAME.zip
        asset_content_type: application/zip

    - uses: actions/upload-artifact@v1
      with:
        name: $REPO_NAME.zip
        path: .
