name: Action 1
on: [ push ]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: rm .travis-disabled.yml
      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: .
