name: Action 2
on:
  workflow_run:
    workflows: [ "Action 1" ]
    types: [ completed ]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: my-artifact
      - run: ls -lah
