name: Lighthouse Tests on Bluehost VPS

on:
  workflow_run:
    workflows: [ "Deploy to Bluehost VPS" ]
    types:
      - completed

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    environment: bluehost-vps
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          spec: tests/cypress/integration/lighthouse.spec.js
        env:
          CYPRESS_baseUrl: ${{ secrets.CYPRESS_BASEURL }}
          CYPRESS_wpUsername: ${{ secrets.CYPRESS_WP_USERNAME }}
          CYPRESS_wpPassword: ${{ secrets.CYPRESS_WP_PASSWORD }}

      - uses: actions/upload-artifact@v1
        with:
          name: lighthouse-logs
          path: logs/cypress.log
