name: Lighthouse Tests on Bluehost VPS

on:
  workflow_run:
    workflows: [ "Deploy to Bluehost VPS" ]
    types:
      - completed

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    environment: bluehost-vps
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          spec: tests/cypress/integration/performance/lighthouse.spec.js
        env:
          CYPRESS_BASE_URL: ${{ secrets.CYPRESS_BASE_URL }}
          CYPRESS_WP_USERNAME: ${{ secrets.CYPRESS_WP_USERNAME }}
          CYPRESS_WP_PASSWORD: ${{ secrets.CYPRESS_WP_PASSWORD }}

      - uses: actions/upload-artifact@v1
        with:
          name: lighthouse-logs
          path: tests/cypress/logs/cypress.log
