

name: Run PHP Code Sniffer
on:
  push:
    branches:
      - main
    paths:
      - '**.php'
jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
    
      # Use PHP 7.4 here for compatibility with the WordPress codesniffer rules.
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer
    
      - name: Install dependencies
        run: composer install
    
      - name: Run PHP Code Sniffer
        run: vendor/bin/phpcs --standard=phpcs.xml -s .

```