name: Performance Tests on Bluehost VPS

on:
  workflow_run:
    workflows: [ "Deploy to Bluehost VPS" ]
    types:
      - completed

jobs:
  load-time:
    runs-on: ubuntu-latest
    environment: bluehost-vps
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          spec: tests/cypress/integration/performance/load-time.spec.js
        env:
          CYPRESS_BASE_URL: ${{ secrets.CYPRESS_BASE_URL }}
          CYPRESS_WP_USERNAME: ${{ secrets.CYPRESS_WP_USERNAME }}
          CYPRESS_WP_PASSWORD: ${{ secrets.CYPRESS_WP_PASSWORD }}

      - uses: actions/upload-artifact@v1
        with:
          name: load-time-logs
          path: tests/cypress/logs/cypress.log
