name: On Push

on:
  release:
    types:
      - created

jobs:
  build:
    name: Run
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Get Event Data
      id: event
      uses: ./.github/actions/github-event-data

    - name: PHP version
      run: php --version

    - name: Set Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Node version
      run: node --version

    - name: NPM version
      run: npm --version

    - name: npm install
      run: npm install

    - name: Build JavaScript
      run: npm prune

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install PHP Dependencies
      run: composer install --prefer-dist --no-progress --no-suggest --no-dev

#    - name: Create Zip
#      run: zip -r ${{ steps.event.repositoryName }}.zip . -x "*.git* node_modules .travis.yml /composer* /package*"

#    - name: List Files
#      run: ls -lah

#    - name: Upload Release Asset
#      id: upload-release-asset
#      uses: actions/upload-release-asset@v1
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      with:
#        upload_url: https://uploads.github.com/repos/${{steps.event.ownerName}}/${{steps.event.repositoryName}}/releases/${{steps.event.releaseId}}/assets{?name,label}"
#        asset_path: ./${{ steps.event.repositoryName }}.zip
#        asset_name: ${{ steps.event.repositoryName }}.zip
#        asset_content_type: application/zip
