name: Trigger Satis Build

on:
  push:
    branches:
      - master
  # release:
  #   types:
  #     - created

jobs:
  webhook:
    name: Send Webhook
    runs-on: ubuntu-latest
    steps:

    - name: Dump GitHub context
      env:
        $CONTEXT: ${{ toJson(github) }}
      run: echo "$CONTEXT"

    - name: Get package
      id: package
      env:
        REPO: ${{ github.repository }}
      run: echo ::set-output name=PACKAGE::${REPO##*/}

    - name: Get version
      id: tag
      run: echo ::set-output name=VERSION::${GITHUB_REF##*/}

    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.WEBHOOK_TOKEN }}
        repository: wpscholar/satis
        event-type: trigger_satis-build
        client-payload: >-
          {
            "vendor": "${{ github.repository_owner }}",
            "package": "${{ steps.package.outputs.PACKAGE }}",
            "version": "${{ steps.tag.outputs.VERSION }}"
          }
