name: Trigger Satis Build

on:
  release:
    types:
      - created

jobs:
  build:
    name: Send Webhook
    runs-on: ubuntu-latest
    steps:

    - name: Webhook
      uses: zzzze/webhook-trigger@master
      with:
        data: '{"event_type": "trigger_satis_build"}'
        webhook_url: ${{ secrets.WEBHOOK_URL }}
        options: '-H "Accept: application/vnd.github.everest-preview+json" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}"'
