name: On Push

on: [push]

env:
  REPO_NAME: hello-world

jobs:
  build:
    name: Run

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: PHP version
      run: php --version

    - name: Run local test action
      uses: ./.github/actions/test
      with:
        who-to-greet: 'Micah'
