name: Trigger Satis Build

on:
  release:
    types:
      - created
      - updated

jobs:
  webhook:
    name: Send Webhook
    runs-on: ubuntu-latest
    steps:

    - name: Send request
      uses: wei/curl@v1
      with:
        args: >
          -X POST ${{ secrets.WEBHOOK_URL }}
          -H 'Accept: application/vnd.github.everest-preview+json'
          -H 'Authorization: token ${{ secrets.WEBHOOK_TOKEN }}'
          --data '{
            "event_type": "trigger_satis_build",
            "client_payload":
              {
                "vendor": "wpscholar",
                "package": "hello-world",
                "version": "${{ github.event.release.id }}"
              }
          }'
