name: Package Plugin

on:
  release:
    types:
      - created

env:
  PACKAGE_NAME: hello-world

jobs:
  build:
    name: Run
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: PHP version
      run: php --version

    - name: Set Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Node version
      run: node --version

    - name: NPM version
      run: npm --version

    - name: npm install
      run: npm install

    - name: Build JavaScript
      run: npm prune

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install PHP Dependencies
      run: composer install --prefer-dist --no-progress --no-suggest --no-dev

    - name: Create Zip
      run: zip -r ${PACKAGE_NAME}.zip . --exclude @./.github/zip-exclude.txt

    - name: List Files
      run: ls -lah

    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: https://uploads.github.com/repos/${{ github.repository }}/releases/${{ github.event.release.id }}/assets{?name,label}
        asset_path: ${{ format('./{0}.zip', ${PACKAGE_NAME}) }}
        asset_name: ${{ format('{0}.zip', ${PACKAGE_NAME}) }}
        asset_content_type: application/zip
