name: run-build
env:
  REPO_NAME: hello-world

on:
  push:
    tags:
      - *

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: PHP version
      run: php --version

    - name: Set Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Node version
      run: node --version

    - name: NPM version
      run: npm --version

    - name: npm install
      run: npm install

    - name: Build JavaScript
      run: npm prune

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install PHP Dependencies
      run: composer install --prefer-dist --no-progress --no-suggest --no-dev

    - name: Create Zip
      run: zip -r $REPO_NAME.zip . -x "*.git* /*node_modules/* .travis.yml /composer* /package*"

    - name: List Files
      run: ls -lah

    - name: GITHUB_REF
      shell: bash
      run: echo "${GITHUB_REF}"
