name: Create Weekly Milestone

on:
  workflow_dispatch:
  schedule:
    # Runs at 00:00 UTC every Monday (customize the schedule as needed)
    - cron: '0 0 * * MON'

jobs:
  create_milestones:
    runs-on: ubuntu-latest
    
    steps:

    - name: Set milestone details
      id: set_milestone
      run: |
        # Set the date format for the milestone title and due date
        DATE=$(date '+%B %d, %Y')  # Format: September 25, 2024
        DATE_ISO8601=$(date -u -d "next week")  # ISO8601 format
        DESCRIPTION="The release is scheduled for $DATE, and PRs should be submitted and made mergeable by EOD $DATE. This means they should have tests passing and merge conflicts resolved. The description for the PR must include details of what is included in the PR and how to test it and preferably new tests supporting the update.\nAny PRs submitted after the deadline will not be included in the release but go in the next release. This includes PRs with tests failing, no description, no screenshots/video demonstrating the update, sufficient Cypress tests, no link to associated JIRA ticket, etc. If no mergeable PRs are submitted for a release, there will be no release that week (unless, of course, there is a need for an out-of-cycle release)."

    - name: Create a new milestone
      id: create_milestone
      run: |
        curl -X POST \
          -H "User-Agent: GitHub-API-Request"
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/milestones \
          -d "{\"title\":\"$DATE Release\", \"description\":\"$DESCRIPTION\", \"due_on\":\"$DATE_ISO8601\", \"state\":\"open\"}"
