name: Shared Files

on: [ push ]

jobs:
  a:
    name: A
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get details
        run: |
          echo "PWD: $PWD"
          echo "github.action_path: ${{ github.action_path }}"
          echo "github.event_path: ${{ github.event_path }}"
          echo "runner.temp: ${{ runner.temp }}"
          echo "runner.workspace: ${{ runner.workspace }}"

      - working-directory: /home/runner
        run: mkdir dist

      - run: cp listener.php /home/runner/dist/listener.php

      - run: ls -lah /home/runner/dist

      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: .

  b:
    name: B
    needs: a
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
          with:
            name: my-artifact
      - run: ls -lah
