name: Cypress Tests

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Run Cypress Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        phpVersion:
          - 7.4
          - 8.0
        wpVersion:
          - 5.9
          - 6.0
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup workflow context
        id: workflow
        working-directory: ${{ runner.temp }}
        env:
          REPO: ${{ github.repository }}
        run: |
          mkdir dist
          echo ::set-output name=DIST::${PWD}/dist
          echo ::set-output name=PACKAGE::${REPO##*/}

      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Show versions
        run: |
          node --version
          npm --version

      - name: NPM Install
        run: npm install

      - name: Create Distribution Copy
        run: rsync -r --exclude-from=.distignore . ${{ steps.workflow.outputs.DIST }}/${{ steps.workflow.outputs.PACKAGE }}

      - name: List Distribution Files
        working-directory: ${{ steps.workflow.outputs.DIST }}
        run: find .

      - name: Configure WordPress
        run: echo '{"core": "WordPress/WordPress#tags/${{ matrix.wpVersion }}","phpVersion": "${{ matrix.phpVersion }}","config":{"WP_DEBUG_DISPLAY":false},"plugins":["${{ steps.workflow.outputs.DIST }}/${{ steps.workflow.outputs.PACKAGE }}"]}' > .wp-env.override.json

      - name: Install WordPress
        run: npx wp-env start

      - name: Run Cypress Tests
        run: npm run test:e2e

      - name: Store screenshots of test failures
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: ./tests/cypress/screenshots

      - name: Check if a debug.log file exists
        id: hasErrors
        run: npx wp-env run wordpress test ! -f /var/www/html/wp-content/debug.log

      - name: Copy debug.log file
        if: ${{ steps.hasErrors.outputs.failure }}
        run: cat /var/www/html/wp-content/debug.log 1>./debug.log 2>/dev/null

      - name: Store debug.log file
        if: ${{ steps.hasErrors.outputs.failure }}
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: ./debug.log
