name: Run WebPageTest on Bluehost VPS

on:
  workflow_run:
    workflows: [ "Deploy to Bluehost VPS" ]
    types:
      - completed

jobs:
  webpagetest:
    runs-on: ubuntu-latest
    steps:

      - name: WebPageTest
        uses: WPO-Foundation/webpagetest-github-action@main
        with:
          apiKey: ${{ secrets.WPT_API_KEY }}
          urls: |
            https://test-bluehost-vps.com
          label: 'test-bluehost-vps.com'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
